// Neumann Admin Dashboard Data
export const neumannDashboardData = {
  stats: {
    totalClients: 28,
    activeClients: 18,
    totalSessions: 342,
    monthlyRevenue: 12500,
    avgSessionValue: 65,
    satisfactionRate: 4.8,
  },
  clients: [
    {
      id: "1",
      name: "Marijn Besseler",
      email: "marijn@example.nl",
      phone: "06-12345678",
      status: "Actief",
      goal: "Revalidatie knieblessure",
      startDate: "2024-03-01",
      nextSession: "2024-12-18",
      type: "1-op-1 Training",
      sessionsCompleted: 42,
      totalSessions: 50,
      progress: 84,
      package: "Revalidatie pakket",
      value: 3250,
    },
    {
      id: "2",
      name: "Kristel Kwant",
      email: "kristel@example.nl",
      phone: "06-23456789",
      status: "Actief",
      goal: "Hernia revalidatie & core stability",
      startDate: "2024-01-15",
      nextSession: "2024-12-19",
      type: "1-op-1 Training",
      sessionsCompleted: 58,
      totalSessions: 60,
      progress: 97,
      package: "Revalidatie pakket",
      value: 3900,
    },
    {
      id: "3",
      name: "Heather Court",
      email: "heather@example.nl",
      phone: "06-34567890",
      status: "Voltooid",
      goal: "Afvallen & kracht opbouwen",
      startDate: "2024-06-01",
      nextSession: null,
      type: "Online coaching",
      sessionsCompleted: 24,
      totalSessions: 24,
      progress: 100,
      package: "Online pakket",
      value: 1200,
    },
    {
      id: "4",
      name: "Fadil Deniz",
      email: "fadil@example.nl",
      phone: "06-45678901",
      status: "Actief",
      goal: "Explosiviteit voor kickboksen",
      startDate: "2024-08-10",
      nextSession: "2024-12-20",
      type: "1-op-1 Training",
      sessionsCompleted: 18,
      totalSessions: 30,
      progress: 60,
      package: "Performance pakket",
      value: 1950,
    },
  ],
  upcomingSessions: [
    { id: "1", client: "Marijn Besseler", date: "2024-12-18", time: "10:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "2", client: "Kristel Kwant", date: "2024-12-19", time: "14:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "3", client: "Fadil Deniz", date: "2024-12-20", time: "16:00", type: "1-op-1 Training", location: "Thuis" },
    { id: "4", client: "Sarah de Vries", date: "2024-12-21", time: "09:00", type: "Duo Training", location: "Park" },
  ],
  revenue: {
    thisMonth: 12500,
    lastMonth: 11800,
    thisYear: 145000,
    growth: 5.9,
  },
  services: [
    {
      id: "1",
      name: "1-op-1 Training aan huis",
      activeClients: 12,
      monthlyRevenue: 7800,
      avgSessionValue: 65,
      sessionsThisMonth: 120,
    },
    {
      id: "2",
      name: "Duo Personal Training",
      activeClients: 4,
      monthlyRevenue: 2400,
      avgSessionValue: 60,
      sessionsThisMonth: 40,
    },
    {
      id: "3",
      name: "Online coaching & voeding",
      activeClients: 8,
      monthlyRevenue: 1600,
      avgSessionValue: 200,
      sessionsThisMonth: 8,
    },
  ],
  recentReviews: [
    {
      name: "Erwin Altena",
      text: "De afgelopen 5 jaar heb ik Nick leren kennen als een enthousiaste jonge Personal Trainer die goed luistert naar de persoon die hij traint.",
      rating: 5,
      date: "2024-11-15",
    },
    {
      name: "Marijn Besseler",
      text: "Door een blessure aan mijn knie is het niet altijd makkelijk om te trainen maar Nick weet me altijd te motiveren om door te gaan.",
      rating: 5,
      date: "2024-11-20",
    },
  ],
};
