import type { Ingredient, MealTemplate } from "./weekmenu";

function meal(
  naam: string,
  tijd: string,
  bereidingswijze: string,
  ingrediënten: Ingredient[]
): MealTemplate {
  return { naam, tijd, bereidingswijze, ingrediënten };
}

export const ONTBIJT_OPTIES: MealTemplate[] = [
  meal("Ontbijt — Kwarkbowl met haver en aardbei", "08:00",
    "Schep magere kwark in een kom. Roer er havermout door en top met aardbeien. Koud serveren.",
    [
      { naam: "Kwark (mager)", portie: "250g", kcal: 143, eiwit: 25, koolhydraten: 9, vetten: 0.5 },
      { naam: "Havermout", portie: "40g", kcal: 144, eiwit: 5, koolhydraten: 24, vetten: 2 },
      { naam: "Aardbeien", portie: "100g", kcal: 32, eiwit: 1, koolhydraten: 8, vetten: 0 },
    ]),
  meal("Ontbijt — Skyr met havermout en appel", "08:00",
    "Serveer skyr koud. Roer havermout erdoor en voeg appelblokjes toe.",
    [
      { naam: "Skyr", portie: "250g", kcal: 148, eiwit: 28, koolhydraten: 10, vetten: 0.5 },
      { naam: "Havermout", portie: "35g", kcal: 126, eiwit: 4, koolhydraten: 21, vetten: 2 },
      { naam: "Appel", portie: "1 middelgroot", kcal: 95, eiwit: 0, koolhydraten: 25, vetten: 0 },
    ]),
  meal("Ontbijt — Overnight oats met yoghurt en banaan", "08:00",
    "Meng havermout, yoghurt en melk. Laat even staan of overnacht in de koelkast. Serveer koud met banaan.",
    [
      { naam: "Havermout", portie: "45g", kcal: 162, eiwit: 5, koolhydraten: 27, vetten: 3 },
      { naam: "Griekse yoghurt (mager)", portie: "150g", kcal: 89, eiwit: 15, koolhydraten: 5, vetten: 0.6 },
      { naam: "Melk (halfvol)", portie: "100ml", kcal: 50, eiwit: 3, koolhydraten: 5, vetten: 1.6 },
      { naam: "Banaan", portie: "1/2 stuk", kcal: 53, eiwit: 1, koolhydraten: 14, vetten: 0 },
    ]),
  meal("Ontbijt — Havermoutpap met bessen", "08:00",
    "Kook havermout kort met water of melk tot een papje, of laat weken. Top met blauwe bessen. Geen vlees.",
    [
      { naam: "Havermout", portie: "50g", kcal: 180, eiwit: 6, koolhydraten: 30, vetten: 3 },
      { naam: "Griekse yoghurt (mager)", portie: "125g", kcal: 74, eiwit: 12.5, koolhydraten: 4.5, vetten: 0.5 },
      { naam: "Blauwe bessen", portie: "80g", kcal: 46, eiwit: 1, koolhydraten: 11, vetten: 0 },
    ]),
  meal("Ontbijt — Yoghurtbowl met aardbei en haver", "08:00",
    "Griekse yoghurt in een kom, havermout erdoor, aardbeien erop. Niet verwarmen.",
    [
      { naam: "Griekse yoghurt (mager)", portie: "200g", kcal: 118, eiwit: 20, koolhydraten: 7, vetten: 0.8 },
      { naam: "Havermout", portie: "40g", kcal: 144, eiwit: 5, koolhydraten: 24, vetten: 2 },
      { naam: "Aardbeien", portie: "120g", kcal: 38, eiwit: 1, koolhydraten: 10, vetten: 0 },
    ]),
  meal("Ontbijt — Kwark met bessen en amandelen", "08:00",
    "Kwark koud serveren met blauwe bessen en een klein handje amandelen.",
    [
      { naam: "Kwark (mager)", portie: "250g", kcal: 143, eiwit: 25, koolhydraten: 9, vetten: 0.5 },
      { naam: "Blauwe bessen", portie: "80g", kcal: 46, eiwit: 1, koolhydraten: 11, vetten: 0 },
      { naam: "Amandelen", portie: "15g", kcal: 87, eiwit: 3, koolhydraten: 3, vetten: 7.5 },
    ]),
  meal("Ontbijt — Skyr bowl met banaan", "08:00",
    "Skyr in een kom, havermout erdoor, banaan in plakjes erop.",
    [
      { naam: "Skyr", portie: "200g", kcal: 118, eiwit: 22, koolhydraten: 8, vetten: 0.4 },
      { naam: "Havermout", portie: "30g", kcal: 108, eiwit: 4, koolhydraten: 18, vetten: 2 },
      { naam: "Banaan", portie: "1 middelgroot", kcal: 105, eiwit: 1, koolhydraten: 27, vetten: 0 },
    ]),
  meal("Ontbijt — Kwark volkoren met appel", "08:00",
    "Kwark met havermout en appel. Koud, snel klaar.",
    [
      { naam: "Kwark (mager)", portie: "200g", kcal: 114, eiwit: 20, koolhydraten: 7, vetten: 0.4 },
      { naam: "Havermout", portie: "30g", kcal: 108, eiwit: 4, koolhydraten: 18, vetten: 2 },
      { naam: "Appel", portie: "1 middelgroot", kcal: 95, eiwit: 0, koolhydraten: 25, vetten: 0 },
    ]),
  meal("Ontbijt — Cottage cheese met tomaat en komkommer", "08:00",
    "Cottage cheese met komkommer en tomaat. Hartig koud ontbijt, geen vlees.",
    [
      { naam: "Cottage cheese", portie: "200g", kcal: 196, eiwit: 22, koolhydraten: 7, vetten: 8.6 },
      { naam: "Komkommer", portie: "100g", kcal: 16, eiwit: 1, koolhydraten: 4, vetten: 0 },
      { naam: "Tomaten", portie: "100g", kcal: 18, eiwit: 1, koolhydraten: 4, vetten: 0 },
      { naam: "Brood (volkoren)", portie: "1 sneetje", kcal: 80, eiwit: 4, koolhydraten: 13, vetten: 1 },
    ]),
  meal("Ontbijt — Havermout met melk en aardbei", "08:00",
    "Havermout met melk tot een papje. Top met aardbeien en een schep magere yoghurt.",
    [
      { naam: "Havermout", portie: "50g", kcal: 180, eiwit: 6, koolhydraten: 30, vetten: 3 },
      { naam: "Melk (halfvol)", portie: "200ml", kcal: 100, eiwit: 6.6, koolhydraten: 9.8, vetten: 3.2 },
      { naam: "Aardbeien", portie: "100g", kcal: 32, eiwit: 1, koolhydraten: 8, vetten: 0 },
      { naam: "Griekse yoghurt (mager)", portie: "100g", kcal: 59, eiwit: 10, koolhydraten: 3.6, vetten: 0.4 },
    ]),
  meal("Ontbijt — Skyr met walnoten en bessen", "08:00",
    "Skyr koud, blauwe bessen erop, walnoten grof hakken en strooien.",
    [
      { naam: "Skyr", portie: "250g", kcal: 148, eiwit: 28, koolhydraten: 10, vetten: 0.5 },
      { naam: "Blauwe bessen", portie: "80g", kcal: 46, eiwit: 1, koolhydraten: 11, vetten: 0 },
      { naam: "Walnoten", portie: "10g", kcal: 65, eiwit: 1.5, koolhydraten: 1.4, vetten: 6.5 },
    ]),
  meal("Ontbijt — Kwark met haver en honingsmaak (fruit)", "08:00",
    "Kwark met havermout en aardbei. Zoet van fruit, geen extra suiker nodig.",
    [
      { naam: "Kwark (vol)", portie: "175g", kcal: 172, eiwit: 21, koolhydraten: 6, vetten: 7.5 },
      { naam: "Havermout", portie: "35g", kcal: 126, eiwit: 4, koolhydraten: 21, vetten: 2 },
      { naam: "Aardbeien", portie: "100g", kcal: 32, eiwit: 1, koolhydraten: 8, vetten: 0 },
    ]),
  meal("Ontbijt — Yoghurt met banaan en amandelen", "08:00",
    "Magere Griekse yoghurt, banaan in plakjes, amandelen erover.",
    [
      { naam: "Griekse yoghurt (mager)", portie: "200g", kcal: 118, eiwit: 20, koolhydraten: 7, vetten: 0.8 },
      { naam: "Banaan", portie: "1 middelgroot", kcal: 105, eiwit: 1, koolhydraten: 27, vetten: 0 },
      { naam: "Amandelen", portie: "10g", kcal: 58, eiwit: 2, koolhydraten: 2, vetten: 5 },
    ]),
  meal("Ontbijt — Skyr overnight oats", "08:00",
    "Havermout + skyr + melk mengen, even laten staan. Koud eten met appel.",
    [
      { naam: "Skyr", portie: "200g", kcal: 118, eiwit: 22, koolhydraten: 8, vetten: 0.4 },
      { naam: "Havermout", portie: "40g", kcal: 144, eiwit: 5, koolhydraten: 24, vetten: 2 },
      { naam: "Melk (mager)", portie: "50ml", kcal: 17, eiwit: 1.7, koolhydraten: 2.5, vetten: 0.1 },
      { naam: "Appel", portie: "1/2 stuk", kcal: 48, eiwit: 0, koolhydraten: 13, vetten: 0 },
    ]),
];

export const LUNCH_OPTIES: MealTemplate[] = [
  meal("Lunch — Kipfilet met zoete aardappel en broccoli", "12:30",
    "Bak de kipfilet in een teflonpan met 1 el olijfolie. Oven of kook zoete aardappel. Stoom of kook broccoli beetgaar. Breng op smaak met peper, zout en paprika.",
    [
      { naam: "Kipfilet", portie: "150g", kcal: 248, eiwit: 46, koolhydraten: 0, vetten: 5 },
      { naam: "Zoete aardappel", portie: "200g", kcal: 180, eiwit: 4, koolhydraten: 41, vetten: 0 },
      { naam: "Broccoli", portie: "150g", kcal: 51, eiwit: 4, koolhydraten: 10, vetten: 1 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Lunch — Kalkoenfilet met rijst en spinazie", "12:30",
    "Bak kalkoenfilet. Kook rijst. Bak spinazie kort in dezelfde pan tot hij slinkt.",
    [
      { naam: "Kalkoenfilet", portie: "150g", kcal: 203, eiwit: 45, koolhydraten: 0, vetten: 1.5 },
      { naam: "Rijst (gekookt)", portie: "150g", kcal: 195, eiwit: 4, koolhydraten: 42, vetten: 0.5 },
      { naam: "Spinazie (rauw)", portie: "150g", kcal: 35, eiwit: 4, koolhydraten: 5, vetten: 0.6 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Lunch — Tonijnsalade op volkoren brood", "12:30",
    "Meng verse of uitgelekte tonijn met komkommer en tomaat. Serveer op 2 sneden volkorenbrood.",
    [
      { naam: "Tonijn (vers)", portie: "130g", kcal: 187, eiwit: 39, koolhydraten: 0, vetten: 1.3 },
      { naam: "Brood (volkoren)", portie: "2 sneden", kcal: 160, eiwit: 8, koolhydraten: 26, vetten: 2 },
      { naam: "Komkommer", portie: "100g", kcal: 16, eiwit: 1, koolhydraten: 4, vetten: 0 },
      { naam: "Tomaten", portie: "100g", kcal: 18, eiwit: 1, koolhydraten: 4, vetten: 0 },
    ]),
  meal("Lunch — Magere rundergehakt met pasta en paprika", "12:30",
    "Bak gehakt rul. Voeg paprika toe. Meng door gekookte pasta. Kruid met oregano en peper.",
    [
      { naam: "Rundergehakt (mager)", portie: "120g", kcal: 300, eiwit: 31, koolhydraten: 0, vetten: 18 },
      { naam: "Pasta (gekookt)", portie: "150g", kcal: 197, eiwit: 7.5, koolhydraten: 39, vetten: 1.5 },
      { naam: "Paprika (rood)", portie: "120g", kcal: 37, eiwit: 1, koolhydraten: 8, vetten: 0 },
    ]),
  meal("Lunch — Gekookte eieren met aardappel en groene bonen", "12:30",
    "Kook eieren 8–9 min (hard). Kook aardappel en groene bonen. Serveer met peper en een klein scheutje olie.",
    [
      { naam: "Ei (heel)", portie: "3 stuks", kcal: 233, eiwit: 20, koolhydraten: 1.5, vetten: 16 },
      { naam: "Aardappel (gekookt)", portie: "200g", kcal: 174, eiwit: 4, koolhydraten: 40, vetten: 0 },
      { naam: "Groene bonen", portie: "150g", kcal: 47, eiwit: 3, koolhydraten: 10, vetten: 0 },
    ]),
  meal("Lunch — Kippendij met quinoa en courgette", "12:30",
    "Bak kippendij uit. Kook quinoa. Bak courgette in plakjes mee tot goudbruin.",
    [
      { naam: "Kippendij", portie: "140g", kcal: 293, eiwit: 36, koolhydraten: 0, vetten: 15 },
      { naam: "Quinoa (gekookt)", portie: "150g", kcal: 180, eiwit: 6.6, koolhydraten: 33, vetten: 2.9 },
      { naam: "Courgette", portie: "150g", kcal: 26, eiwit: 2, koolhydraten: 5, vetten: 0 },
    ]),
  meal("Lunch — Kabeljauw met zoete aardappel en bloemkool", "12:30",
    "Bak of stoom de kabeljauw. Oven zoete aardappel. Bloemkool stomen of roosteren.",
    [
      { naam: "Kabeljauw", portie: "170g", kcal: 139, eiwit: 31, koolhydraten: 0, vetten: 1 },
      { naam: "Zoete aardappel", portie: "180g", kcal: 162, eiwit: 3, koolhydraten: 37, vetten: 0 },
      { naam: "Bloemkool", portie: "150g", kcal: 38, eiwit: 3, koolhydraten: 8, vetten: 0 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Lunch — Kipwrap met paprika en cottage cheese", "12:30",
    "Bak kipreepjes. Beleg volkoren brood of wrap-vervanger met cottage cheese, paprika en kip.",
    [
      { naam: "Kipfilet", portie: "140g", kcal: 231, eiwit: 43, koolhydraten: 0, vetten: 5 },
      { naam: "Brood (volkoren)", portie: "2 sneden", kcal: 160, eiwit: 8, koolhydraten: 26, vetten: 2 },
      { naam: "Paprika (rood)", portie: "100g", kcal: 31, eiwit: 1, koolhydraten: 7, vetten: 0 },
      { naam: "Cottage cheese", portie: "80g", kcal: 78, eiwit: 9, koolhydraten: 2.7, vetten: 3.4 },
    ]),
  meal("Lunch — Zalmsalade met volkoren pasta", "12:30",
    "Bak zalm of gebruik restje zalm koud. Meng door pasta met komkommer. Citroen erover.",
    [
      { naam: "Zalm", portie: "130g", kcal: 270, eiwit: 38, koolhydraten: 0, vetten: 12 },
      { naam: "Volkoren pasta (gekookt)", portie: "140g", kcal: 174, eiwit: 7, koolhydraten: 35, vetten: 1.5 },
      { naam: "Komkommer", portie: "100g", kcal: 16, eiwit: 1, koolhydraten: 4, vetten: 0 },
    ]),
  meal("Lunch — Mager rund met linzen en wortel", "12:30",
    "Bak rundreepjes. Kook linzen of gebruik uit blik (spoelen). Wortel meebakken of koken.",
    [
      { naam: "Rundvlees (mager)", portie: "120g", kcal: 300, eiwit: 31, koolhydraten: 0, vetten: 18 },
      { naam: "Linzen (gekookt)", portie: "150g", kcal: 174, eiwit: 14, koolhydraten: 30, vetten: 0.6 },
      { naam: "Wortelen (rauw)", portie: "100g", kcal: 41, eiwit: 0.9, koolhydraten: 10, vetten: 0.2 },
    ]),
  meal("Lunch — Tofu roerbak met bruine rijst", "12:30",
    "Pers tofu, bak goudbruin. Roerbak paprika of paksoi. Serveer met bruine rijst.",
    [
      { naam: "Tofu", portie: "180g", kcal: 137, eiwit: 14, koolhydraten: 3.4, vetten: 8.6 },
      { naam: "Bruine rijst (gekookt)", portie: "150g", kcal: 167, eiwit: 4, koolhydraten: 35, vetten: 1 },
      { naam: "Paprika (rood)", portie: "120g", kcal: 37, eiwit: 1, koolhydraten: 8, vetten: 0 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Lunch — Kipfilet met aardappel en groene bonen", "12:30",
    "Grill of bak kip. Kook aardappel in de schil. Groene bonen 6 min koken.",
    [
      { naam: "Kipfilet", portie: "160g", kcal: 264, eiwit: 50, koolhydraten: 0, vetten: 6 },
      { naam: "Aardappel (gekookt)", portie: "180g", kcal: 157, eiwit: 3.6, koolhydraten: 36, vetten: 0 },
      { naam: "Groene bonen", portie: "150g", kcal: 47, eiwit: 3, koolhydraten: 10, vetten: 0 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Lunch — Makreel met aardappel en sla", "12:30",
    "Bak makreel kort op de huid. Kook aardappel. Serveer met komkommer/tomaat als salade.",
    [
      { naam: "Makreel", portie: "140g", kcal: 287, eiwit: 27, koolhydraten: 0, vetten: 20 },
      { naam: "Aardappel (gekookt)", portie: "180g", kcal: 157, eiwit: 3.6, koolhydraten: 36, vetten: 0 },
      { naam: "Komkommer", portie: "100g", kcal: 16, eiwit: 1, koolhydraten: 4, vetten: 0 },
      { naam: "Tomaten", portie: "80g", kcal: 14, eiwit: 1, koolhydraten: 3, vetten: 0 },
    ]),
  meal("Lunch — Garnalen met rijst en broccoli", "12:30",
    "Bak garnalen 2–3 min tot ze roze zijn. Kook rijst en broccoli. Knoflook en citroen naar smaak.",
    [
      { naam: "Garnalen", portie: "150g", kcal: 149, eiwit: 36, koolhydraten: 0, vetten: 0.5 },
      { naam: "Rijst (gekookt)", portie: "150g", kcal: 195, eiwit: 4, koolhydraten: 42, vetten: 0.5 },
      { naam: "Broccoli", portie: "150g", kcal: 51, eiwit: 4, koolhydraten: 10, vetten: 1 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Lunch — Kalkoen met zoete aardappel en spinazie", "12:30",
    "Bak kalkoen. Oven zoete aardappel. Spinazie kort laten slinken in de pan.",
    [
      { naam: "Kalkoenfilet", portie: "160g", kcal: 216, eiwit: 48, koolhydraten: 0, vetten: 1.6 },
      { naam: "Zoete aardappel", portie: "180g", kcal: 162, eiwit: 3, koolhydraten: 37, vetten: 0 },
      { naam: "Spinazie (rauw)", portie: "120g", kcal: 28, eiwit: 3.5, koolhydraten: 4, vetten: 0.5 },
    ]),
  meal("Lunch — Tempeh roerbak met quinoa", "12:30",
    "Bak tempeh in blokjes. Roerbak courgette. Serveer met quinoa.",
    [
      { naam: "Tempeh", portie: "150g", kcal: 290, eiwit: 29, koolhydraten: 14, vetten: 16 },
      { naam: "Quinoa (gekookt)", portie: "140g", kcal: 168, eiwit: 6, koolhydraten: 31, vetten: 2.7 },
      { naam: "Courgette", portie: "150g", kcal: 26, eiwit: 2, koolhydraten: 5, vetten: 0 },
    ]),
  meal("Lunch — Kikkererwten met volkoren pasta en paprika", "12:30",
    "Kook pasta. Bak paprika. Voeg spoelde kikkererwten toe en laat warm worden.",
    [
      { naam: "Kikkererwten (gekookt)", portie: "180g", kcal: 295, eiwit: 16, koolhydraten: 49, vetten: 4.7 },
      { naam: "Volkoren pasta (gekookt)", portie: "140g", kcal: 174, eiwit: 7, koolhydraten: 35, vetten: 1.5 },
      { naam: "Paprika (rood)", portie: "120g", kcal: 37, eiwit: 1, koolhydraten: 8, vetten: 0 },
      { naam: "Feta", portie: "40g", kcal: 100, eiwit: 6, koolhydraten: 1, vetten: 8 },
    ]),
  meal("Lunch — Linzenstoof met zoete aardappel", "12:30",
    "Kook of warm linzen. Serveer met oven zoete aardappel en spinazie.",
    [
      { naam: "Linzen (gekookt)", portie: "200g", kcal: 232, eiwit: 18, koolhydraten: 40, vetten: 0.8 },
      { naam: "Zoete aardappel", portie: "180g", kcal: 162, eiwit: 3, koolhydraten: 37, vetten: 0 },
      { naam: "Spinazie (rauw)", portie: "100g", kcal: 23, eiwit: 3, koolhydraten: 4, vetten: 0.4 },
    ]),
  meal("Lunch — Cottage cheese bowl met volkoren brood", "12:30",
    "Cottage cheese met tomaat en komkommer. 2 sneden volkoren brood erbij.",
    [
      { naam: "Cottage cheese", portie: "200g", kcal: 196, eiwit: 22, koolhydraten: 7, vetten: 8.6 },
      { naam: "Brood (volkoren)", portie: "2 sneden", kcal: 160, eiwit: 8, koolhydraten: 26, vetten: 2 },
      { naam: "Tomaten", portie: "100g", kcal: 18, eiwit: 1, koolhydraten: 4, vetten: 0 },
      { naam: "Komkommer", portie: "100g", kcal: 16, eiwit: 1, koolhydraten: 4, vetten: 0 },
    ]),
];

export const DINER_OPTIES: MealTemplate[] = [
  meal("Diner — Zalm met quinoa en groene bonen", "18:00",
    "Bak zalm op de huid 3–4 min per kant. Kook quinoa. Stoom groene bonen. Avocado in plakjes erbij.",
    [
      { naam: "Zalm", portie: "150g", kcal: 312, eiwit: 44, koolhydraten: 0, vetten: 14 },
      { naam: "Quinoa (gekookt)", portie: "120g", kcal: 144, eiwit: 5, koolhydraten: 26, vetten: 2.3 },
      { naam: "Groene bonen", portie: "150g", kcal: 44, eiwit: 2, koolhydraten: 10, vetten: 0 },
      { naam: "Avocado", portie: "40g", kcal: 64, eiwit: 1, koolhydraten: 3, vetten: 6 },
    ]),
  meal("Diner — Kipfilet met bruine rijst en broccoli", "18:00",
    "Bak of oven kipfilet. Kook bruine rijst. Broccoli stomen. 1 el olie voor de pan.",
    [
      { naam: "Kipfilet", portie: "160g", kcal: 264, eiwit: 50, koolhydraten: 0, vetten: 6 },
      { naam: "Bruine rijst (gekookt)", portie: "150g", kcal: 167, eiwit: 4, koolhydraten: 35, vetten: 1 },
      { naam: "Broccoli", portie: "150g", kcal: 51, eiwit: 4, koolhydraten: 10, vetten: 1 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Diner — Mager rundvlees met aardappel en spinazie", "18:00",
    "Grill of bak magere biefstuk/runderreep. Kook aardappel. Spinazie kort bakken.",
    [
      { naam: "Rundvlees (mager)", portie: "140g", kcal: 350, eiwit: 36, koolhydraten: 0, vetten: 21 },
      { naam: "Aardappel (gekookt)", portie: "200g", kcal: 174, eiwit: 4, koolhydraten: 40, vetten: 0 },
      { naam: "Spinazie (gekookt)", portie: "150g", kcal: 35, eiwit: 4.5, koolhydraten: 6, vetten: 0.5 },
    ]),
  meal("Diner — Makreel met zoete aardappel en paprika", "18:00",
    "Bak makreel kort. Zoete aardappel in de oven. Paprika meeroosteren.",
    [
      { naam: "Makreel", portie: "140g", kcal: 287, eiwit: 27, koolhydraten: 0, vetten: 20 },
      { naam: "Zoete aardappel", portie: "180g", kcal: 162, eiwit: 3, koolhydraten: 37, vetten: 0 },
      { naam: "Paprika (rood)", portie: "120g", kcal: 37, eiwit: 1, koolhydraten: 8, vetten: 0 },
    ]),
  meal("Diner — Garnalenpasta met courgette", "18:00",
    "Kook pasta. Bak garnalen snel. Courgette in linten of plakjes meebakken. Citroen en peper.",
    [
      { naam: "Garnalen", portie: "150g", kcal: 149, eiwit: 36, koolhydraten: 0, vetten: 0.5 },
      { naam: "Pasta (gekookt)", portie: "150g", kcal: 197, eiwit: 7.5, koolhydraten: 39, vetten: 1.5 },
      { naam: "Courgette", portie: "150g", kcal: 26, eiwit: 2, koolhydraten: 5, vetten: 0 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Diner — Kalkoenfilet met quinoa en boerenkool", "18:00",
    "Bak kalkoen. Kook quinoa. Boerenkool 5 min meebakken of stomen.",
    [
      { naam: "Kalkoenfilet", portie: "160g", kcal: 216, eiwit: 48, koolhydraten: 0, vetten: 1.6 },
      { naam: "Quinoa (gekookt)", portie: "140g", kcal: 168, eiwit: 6, koolhydraten: 31, vetten: 2.7 },
      { naam: "Boerenkool", portie: "120g", kcal: 59, eiwit: 5, koolhydraten: 11, vetten: 1 },
    ]),
  meal("Diner — Kabeljauw met rijst en broccoli", "18:00",
    "Kabeljauw in de oven 12–15 min of in de pan. Kook rijst en broccoli.",
    [
      { naam: "Kabeljauw", portie: "170g", kcal: 139, eiwit: 31, koolhydraten: 0, vetten: 1 },
      { naam: "Rijst (gekookt)", portie: "160g", kcal: 208, eiwit: 4, koolhydraten: 45, vetten: 0.5 },
      { naam: "Broccoli", portie: "150g", kcal: 51, eiwit: 4, koolhydraten: 10, vetten: 1 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Diner — Kip-roerbak met rijst en paprika", "18:00",
    "Kip in reepjes bakken. Paprika mee roerbakken. Serveer met bruine rijst.",
    [
      { naam: "Kipfilet", portie: "150g", kcal: 248, eiwit: 46, koolhydraten: 0, vetten: 5 },
      { naam: "Bruine rijst (gekookt)", portie: "150g", kcal: 167, eiwit: 4, koolhydraten: 35, vetten: 1 },
      { naam: "Paprika (rood)", portie: "120g", kcal: 37, eiwit: 1, koolhydraten: 8, vetten: 0 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Diner — Rundergehakt met volkoren pasta", "18:00",
    "Bak gehakt. Courgette meebakken. Meng door volkoren pasta. Italiaanse kruiden.",
    [
      { naam: "Rundergehakt (mager)", portie: "130g", kcal: 325, eiwit: 34, koolhydraten: 0, vetten: 20 },
      { naam: "Volkoren pasta (gekookt)", portie: "150g", kcal: 186, eiwit: 7.5, koolhydraten: 37, vetten: 1.5 },
      { naam: "Courgette", portie: "150g", kcal: 26, eiwit: 2, koolhydraten: 5, vetten: 0 },
    ]),
  meal("Diner — Tonijn met quinoa en spinazie", "18:00",
    "Bak tonijnsteak kort (roze binnenkant mag). Quinoa koken. Spinazie laten slinken.",
    [
      { naam: "Tonijn (vers)", portie: "150g", kcal: 216, eiwit: 45, koolhydraten: 0, vetten: 1.5 },
      { naam: "Quinoa (gekookt)", portie: "140g", kcal: 168, eiwit: 6, koolhydraten: 31, vetten: 2.7 },
      { naam: "Spinazie (rauw)", portie: "120g", kcal: 28, eiwit: 3.5, koolhydraten: 4, vetten: 0.5 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Diner — Groente-omelet met volkoren brood", "18:00",
    "Klop eieren, bak omelet met broccoli. Serveer met volkoren brood.",
    [
      { naam: "Ei (heel)", portie: "3 stuks", kcal: 233, eiwit: 20, koolhydraten: 1.5, vetten: 16 },
      { naam: "Broccoli", portie: "150g", kcal: 51, eiwit: 4, koolhydraten: 10, vetten: 1 },
      { naam: "Brood (volkoren)", portie: "2 sneden", kcal: 160, eiwit: 8, koolhydraten: 26, vetten: 2 },
    ]),
  meal("Diner — Varkenshaas met zoete aardappel en boerenkool", "18:00",
    "Bak varkenshaas tot 63–65°C kern. Zoete aardappel oven. Boerenkool meebakken.",
    [
      { naam: "Varkenshaas", portie: "160g", kcal: 229, eiwit: 35, koolhydraten: 0, vetten: 10 },
      { naam: "Zoete aardappel", portie: "180g", kcal: 162, eiwit: 3, koolhydraten: 37, vetten: 0 },
      { naam: "Boerenkool", portie: "120g", kcal: 59, eiwit: 5, koolhydraten: 11, vetten: 1 },
    ]),
  meal("Diner — Kipfilet met aardappel en bloemkool", "18:00",
    "Ovenkip of pan. Kook aardappel. Bloemkool roosteren of koken.",
    [
      { naam: "Kipfilet", portie: "160g", kcal: 264, eiwit: 50, koolhydraten: 0, vetten: 6 },
      { naam: "Aardappel (gekookt)", portie: "180g", kcal: 157, eiwit: 3.6, koolhydraten: 36, vetten: 0 },
      { naam: "Bloemkool", portie: "150g", kcal: 38, eiwit: 3, koolhydraten: 8, vetten: 0 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Diner — Zalm met aardappel en broccoli", "18:00",
    "Zalm in de oven 12 min op 200°C. Kook aardappel en broccoli.",
    [
      { naam: "Zalm", portie: "150g", kcal: 312, eiwit: 44, koolhydraten: 0, vetten: 14 },
      { naam: "Aardappel (gekookt)", portie: "180g", kcal: 157, eiwit: 3.6, koolhydraten: 36, vetten: 0 },
      { naam: "Broccoli", portie: "150g", kcal: 51, eiwit: 4, koolhydraten: 10, vetten: 1 },
    ]),
  meal("Diner — Kippendij met rijst en spinazie", "18:00",
    "Bak kippendij goed door. Kook rijst. Spinazie in de pan tot hij slinkt.",
    [
      { naam: "Kippendij", portie: "150g", kcal: 314, eiwit: 39, koolhydraten: 0, vetten: 16 },
      { naam: "Rijst (gekookt)", portie: "150g", kcal: 195, eiwit: 4, koolhydraten: 42, vetten: 0.5 },
      { naam: "Spinazie (rauw)", portie: "150g", kcal: 35, eiwit: 4, koolhydraten: 5, vetten: 0.6 },
    ]),
  meal("Diner — Tofu met bruine rijst en broccoli", "18:00",
    "Tofu bakken tot krokant. Broccoli stomen. Bruine rijst koken. Sojasaus naar smaak (niet meegerekend).",
    [
      { naam: "Tofu", portie: "200g", kcal: 152, eiwit: 16, koolhydraten: 3.8, vetten: 9.6 },
      { naam: "Bruine rijst (gekookt)", portie: "160g", kcal: 178, eiwit: 4.2, koolhydraten: 37, vetten: 1.1 },
      { naam: "Broccoli", portie: "150g", kcal: 51, eiwit: 4, koolhydraten: 10, vetten: 1 },
      { naam: "Olijfolie", portie: "1 el", kcal: 120, eiwit: 0, koolhydraten: 0, vetten: 14 },
    ]),
  meal("Diner — Linzen met aardappel en boerenkool", "18:00",
    "Warm linzen. Kook aardappel. Boerenkool kort bakken of stomen.",
    [
      { naam: "Linzen (gekookt)", portie: "200g", kcal: 232, eiwit: 18, koolhydraten: 40, vetten: 0.8 },
      { naam: "Aardappel (gekookt)", portie: "180g", kcal: 157, eiwit: 3.6, koolhydraten: 36, vetten: 0 },
      { naam: "Boerenkool", portie: "120g", kcal: 59, eiwit: 5, koolhydraten: 11, vetten: 1 },
    ]),
  meal("Diner — Tempeh met zoete aardappel en spinazie", "18:00",
    "Bak tempeh. Oven zoete aardappel. Spinazie laten slinken.",
    [
      { naam: "Tempeh", portie: "160g", kcal: 309, eiwit: 30, koolhydraten: 14, vetten: 18 },
      { naam: "Zoete aardappel", portie: "180g", kcal: 162, eiwit: 3, koolhydraten: 37, vetten: 0 },
      { naam: "Spinazie (rauw)", portie: "120g", kcal: 28, eiwit: 3.5, koolhydraten: 4, vetten: 0.5 },
    ]),
];

export const SNACK_OPTIES: MealTemplate[] = [
  meal("Tussendoortje — Kwark met amandelen", "10:00",
    "Magere kwark met een klein handje amandelen.",
    [
      { naam: "Kwark (mager)", portie: "200g", kcal: 114, eiwit: 20, koolhydraten: 7, vetten: 0.4 },
      { naam: "Amandelen", portie: "15g", kcal: 87, eiwit: 3, koolhydraten: 3, vetten: 7.5 },
    ]),
  meal("Tussendoortje — Yoghurt met appel", "15:00",
    "Magere Griekse yoghurt met een appel in partjes.",
    [
      { naam: "Griekse yoghurt (mager)", portie: "150g", kcal: 89, eiwit: 15, koolhydraten: 5, vetten: 0.6 },
      { naam: "Appel", portie: "1 middelgroot", kcal: 95, eiwit: 0, koolhydraten: 25, vetten: 0 },
    ]),
  meal("Tussendoortje — Skyr met blauwe bessen", "10:00",
    "Skyr koud met blauwe bessen.",
    [
      { naam: "Skyr", portie: "200g", kcal: 118, eiwit: 22, koolhydraten: 8, vetten: 0.4 },
      { naam: "Blauwe bessen", portie: "80g", kcal: 46, eiwit: 1, koolhydraten: 11, vetten: 0 },
    ]),
  meal("Tussendoortje — Yoghurt havermout aardbei", "15:00",
    "Yoghurt met een lepel havermout en aardbei. Eetlepeltje, geen baksel.",
    [
      { naam: "Griekse yoghurt (mager)", portie: "150g", kcal: 89, eiwit: 15, koolhydraten: 5, vetten: 0.6 },
      { naam: "Havermout", portie: "20g", kcal: 72, eiwit: 2.5, koolhydraten: 12, vetten: 1 },
      { naam: "Aardbeien", portie: "80g", kcal: 26, eiwit: 1, koolhydraten: 6, vetten: 0 },
    ]),
  meal("Tussendoortje — Kwark met walnoten", "10:00",
    "Kwark met grof gehakte walnoten.",
    [
      { naam: "Kwark (mager)", portie: "175g", kcal: 100, eiwit: 17.5, koolhydraten: 6, vetten: 0.4 },
      { naam: "Walnoten", portie: "15g", kcal: 98, eiwit: 2, koolhydraten: 2, vetten: 10 },
    ]),
  meal("Tussendoortje — Appel met amandelen", "15:00",
    "Appel in partjes met amandelen. Handig onderweg.",
    [
      { naam: "Appel", portie: "1 middelgroot", kcal: 95, eiwit: 0, koolhydraten: 25, vetten: 0 },
      { naam: "Amandelen", portie: "20g", kcal: 116, eiwit: 4, koolhydraten: 4, vetten: 10 },
    ]),
  meal("Tussendoortje — Kwark met banaan", "10:00",
    "Magere kwark met een halve banaan.",
    [
      { naam: "Kwark (mager)", portie: "200g", kcal: 114, eiwit: 20, koolhydraten: 7, vetten: 0.4 },
      { naam: "Banaan", portie: "1/2 stuk", kcal: 53, eiwit: 1, koolhydraten: 14, vetten: 0 },
    ]),
  meal("Tussendoortje — Cottage cheese met komkommer", "15:00",
    "Cottage cheese met komkommerschijfjes. Hartig tussendoortje.",
    [
      { naam: "Cottage cheese", portie: "150g", kcal: 147, eiwit: 16.5, koolhydraten: 5, vetten: 6.5 },
      { naam: "Komkommer", portie: "100g", kcal: 16, eiwit: 1, koolhydraten: 4, vetten: 0 },
    ]),
  meal("Tussendoortje — Skyr nature", "10:00",
    "Een bak skyr, klaar. Neem mee in een bakje.",
    [
      { naam: "Skyr", portie: "200g", kcal: 118, eiwit: 22, koolhydraten: 8, vetten: 0.4 },
    ]),
  meal("Tussendoortje — Kwark met aardbei", "15:00",
    "Kwark met aardbeien. Geen suiker nodig.",
    [
      { naam: "Kwark (mager)", portie: "200g", kcal: 114, eiwit: 20, koolhydraten: 7, vetten: 0.4 },
      { naam: "Aardbeien", portie: "100g", kcal: 32, eiwit: 1, koolhydraten: 8, vetten: 0 },
    ]),
  meal("Tussendoortje — Yoghurt met bessen", "20:00",
    "Avondtussendoortje: magere yoghurt met blauwe bessen.",
    [
      { naam: "Griekse yoghurt (mager)", portie: "175g", kcal: 103, eiwit: 17.5, koolhydraten: 6, vetten: 0.7 },
      { naam: "Blauwe bessen", portie: "60g", kcal: 34, eiwit: 0.5, koolhydraten: 8, vetten: 0 },
    ]),
  meal("Tussendoortje — Ei en komkommer", "15:00",
    "2 gekookte eieren met komkommer. Hartig, eiwitrijk.",
    [
      { naam: "Ei (heel)", portie: "2 stuks", kcal: 155, eiwit: 13, koolhydraten: 1, vetten: 11 },
      { naam: "Komkommer", portie: "100g", kcal: 16, eiwit: 1, koolhydraten: 4, vetten: 0 },
    ]),
];

export type SchemaPreset = {
  id: string;
  naam: string;
  beschrijving: string;
  styles: string[];
  preferredProteins: string[];
  mealCount: number;
};

export const SCHEMA_PRESETS: SchemaPreset[] = [
  {
    id: "onderhoud",
    naam: "Gebalanceerd weekschema",
    beschrijving: "7 unieke dagen: kip, vis, rund, kalkoen en zuivel. Standaard voor de meeste klanten.",
    styles: ["Gebalanceerd"],
    preferredProteins: [],
    mealCount: 5,
  },
  {
    id: "eiwitrijk",
    naam: "Eiwitrijk (cut / recomp)",
    beschrijving: "Hoog eiwit, magere zuivel, kip, vis en mager rund. Porties schalen naar het kcal-doel.",
    styles: ["Eiwitrijk"],
    preferredProteins: ["Kip", "Rundvlees", "Vis", "Eieren"],
    mealCount: 5,
  },
  {
    id: "spieropbouw",
    naam: "Spieropbouw",
    beschrijving: "Meer koolhydraten bij lunch/diner (rijst, aardappel, pasta) plus hoog eiwit.",
    styles: ["Koolhydraatrijk", "Eiwitrijk"],
    preferredProteins: ["Kip", "Rundvlees", "Eieren"],
    mealCount: 5,
  },
  {
    id: "kip-vis",
    naam: "Kip & vis",
    beschrijving: "Geen rood vlees. Kip, kalkoen en vis wisselen door de week.",
    styles: ["Gebalanceerd"],
    preferredProteins: ["Kip", "Vis", "Zalm", "Tonijn"],
    mealCount: 5,
  },
  {
    id: "vegetarisch",
    naam: "Vegetarisch",
    beschrijving: "Eieren, zuivel, tofu en tempeh. Geen vlees of vis.",
    styles: ["Vegetarisch"],
    preferredProteins: [],
    mealCount: 5,
  },
  {
    id: "lowcarb",
    naam: "Low-carb",
    beschrijving: "Minder rijst/pasta/haver, meer eiwit en groente. Geschikt bij strakker koolhydraatdoel.",
    styles: ["Low-carb", "Eiwitrijk"],
    preferredProteins: ["Kip", "Vis", "Eieren", "Rundvlees"],
    mealCount: 4,
  },
];
